### ISSUE TITLE
Crashing on Mac on startup

### ISSUE THREAD

**Issue by DanB91** [bztsrc/qemu-raspi3#2]
Compiled and ran on MacOS 10.13.1.
After running **qemu-system-arm -machine raspi3** the program crashes immediately with the message 
"ERROR:/<home_dir>/qemu-raspi3/qom/object.c:363:object_initialize_with_type: assertion failed: (type != NULL)"

Here's the stacktrace:

frame #5: 0x0000000100358aed qemu-system-arm\`object_initialize_with_type(data=0x000000011c018078, size=126120, type=0x0000000000000000) at object.c:363 [opt]
frame #6: 0x000000010010adbb qemu-system-arm\`bcm2837_init(obj=0x000000011c018000) at bcm2837.c:34 [opt]
frame #7: 0x0000000100358a3d qemu-system-arm\`object_initialize_with_type(data=0x000000011c018000, size=523328, type=0x0000000102051d40) at object.c:375 [opt]
frame #8: 0x000000010010baf7 qemu-system-arm\`raspi3_init(machine=0x00000001020d1180) at raspi.c:190 [opt]
frame #9: 0x000000010017c6ed qemu-system-arm\`qemu_main(argc=<unavailable>, argv=0x00000001004755e2, envp=<unavailable>) at vl.c:4744 [opt]
frame #10: 0x000000010033b5de qemu-system-arm\`-[QemuCocoaAppController startEmulationWithArgc:argv:](self=<unavailable>, _cmd=<unavailable>, argc=<unavailable>, argv=<unavailable>) at cocoa.m:1016 [opt]

I am not familiar with qemu development, but it looks like the "cortex-a53-arm-cpu" string is not in the type hash map.  Is there some configuration I am missing?

Thanks!

**Comment by bztsrc** [comment]
Probably. Chances are you haven't configured qemu for arm. This has nothing to do with the patch I've made, as that does not add new cpu to qemu.
