### ISSUE TITLE
Can't build under ubuntu 16.10

### ISSUE THREAD

**Issue by MatthiasJentsch** [bztsrc/qemu-raspi3#3]
I can't build it under ubuntu 16.10. I get the following error message:

/qemu-raspi3/hw/arm/raspi.c: In function ‘setup_boot’:
/qemu-raspi3/hw/arm/raspi.c:104:11: error: ‘entry’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         r = load_image_targphys(machine->firmware, entry,
         ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                 ram_size - entry);
                                 ~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
/qemu-raspi3/rules.mak:66: die Regel für Ziel „hw/arm/raspi.o“ scheiterte
make[1]: *** [hw/arm/raspi.o] Fehler 1
Makefile:327: die Regel für Ziel „subdir-aarch64-softmmu“ scheiterte
make: *** [subdir-aarch64-softmmu] Fehler 2

**Comment by bztsrc** [comment]
Dear HorstBock,

For qemu compilation problems please contact qemu or ubuntu support. It works for me, compiles without errors. Quick fix for your configuration: in raspi.c line 80 replace ";" with "=0;".

Bests,
bzt

**Comment by bztsrc** [comment]
Commited a minor modification that will solve your problem.
