### ISSUE TITLE
Qemu upstream pull request

### ISSUE THREAD

**Issue by SilverOnemi** [bztsrc/qemu-raspi3#4]
Hi,

Very interesting project thank you !!! I was wondering if there are any reasons why you haven't sent a pull request to the official qemu repo? I assume they would be very happy to have this.

Best Regards,
Humberto Carvalho

**Comment by SilverOnemi** [comment]
Never mind, i found more information here:
https://www.raspberrypi.org/forums/viewtopic.php?t=195565

I believe you provide a nice answer to my query. 

Thanks again for your contribution :)

Best Regards,
Humberto Carvalho

**Comment by bztsrc** [comment]
Hi Humberto,

Thank you! Just for completeness I repeat my answer here. Qemu maintainers do not use pull requests from contributors, they require a [patch via email](https://wiki.qemu.org/Contribute/SubmitAPatch).
> I've sent the rpi3 patch to qemu-devel, and they asked for some modifications. Now there's already a pending patch that implements some of those, and I'm awaiting for that patch. Once it's merged with the mainline, I'll resend my patch, so sooner or later rpi3 will make it through to the qemu mainline, and sooner or later you'll have it with the standard raspbian qemu package.

Bests,
bzt

**Comment by bztsrc** [comment]
Follow up.

After 3 months, I had enough waiting for Alistair's patch and rewrote mine regardless. I've sent the diff to qemu-devel again, let's see what happens.

bzt
