### ISSUE TITLE
Compile for Windows?

### ISSUE THREAD

**Issue by gspitman** [bztsrc/qemu-raspi3#6]
Is there a way to compile this into a windows bianary?

**Comment by bztsrc** [comment]
I don't have Win, so I cannot help with the details, I'm sorry.
But yes, should be done the same way you would normally compile qemu on Windows. My patch has nothing OS specific in it.

**Comment by bztsrc** [comment]
Since the patch made through the mainline, sooner or later windows binaries of qemu will have raspi3.
