### ISSUE TITLE
Raspi 1 / zero support?

### ISSUE THREAD

**Issue by piranna** [bztsrc/qemu-raspi3#7]
I've revised your code and seems fairly easy to add a new platform, what about adding also support for original Raspi and Raspi Zero (they are mostly the same)? What things would need to be added to have support for it?

**Comment by bztsrc** [comment]
Those boards don't support 64 bit. So no, I won't add support for them. If you want to write bare metal applications for the original Raspi or Raspi Zero I recommend to use one of the other tutorials listed on the main page on the raspi3-tutorials repo.

**Comment by piranna** [comment]
I was not following the tutorials but instead interested on using it on [NodeOS](http://node-os.com/). Anyway, the 64 bits argument is fair for me :-)
